language: node_js

node_js:
  - "node"

install:
  - npm install

script:
  - npm run build  

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: ds-site/build
  target_branch: gh-pages

cache:
  directories:
    - 'node_modules'
    - 'ds-site/node_modules'

notifications:
  email:
    on_success: never
    on_failure: always
